document.write("    <!-- Navigation -->");
document.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">");
document.write("        <div class=\"container\">");
document.write("            <!-- Brand and toggle get grouped for better mobile display -->");
document.write("            <div class=\"navbar-header\">");
document.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">");
document.write("                    <span class=\"sr-only\">Toggle navigation<\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                <\/button>");
document.write("                <a class=\"navbar-brand\" href=\"index.php\">Assist-U<\/a>");
document.write("            <\/div>");
document.write("            <!-- Collect the nav links, forms, and other content for toggling -->");
document.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.write("                <ul class=\"nav navbar-nav\">");
document.write("                    <li>");
document.write("                        <a href=\"about.php\">About<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"postings.php\">View postings<\/a>");
document.write("                    <\/li>");
document.write("                <\/ul>");
document.write("			 <ul class=\"nav navbar-nav navbar-right\">");
document.write("        <li><a href=\"login.php\">Log in<\/a><\/li>");
document.write("		<li><a href=\"signup.php\">Sign up<\/a><\/li>");
document.write("		<\/ul>");
document.write("		<\/div>");
document.write("            <!-- \/.navbar-collapse -->");
document.write("        <\/div>");
document.write("        <!-- \/.container -->");
document.write("    <\/nav>");
document.write("	");
